[workspace]
authors = ["Paul Rohel <paul.rohel@cnes.fr>"]
channels = ["conda-forge"]
name = "TP OPTMI SC"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
matplotlib = ">=3.10.7,<4"
numpy = ">=2.3.4,<3"
ipykernel = ">=7.1.0,<8"
scipy = ">=1.16.3,<2"
jupyter = ">=1.1.1,<2"
